# 03. Data Preprocessing & Feature Engineering

## Objective

This notebook prepares the cleaned dataset for SQL analysis and Power BI dashboard development.

The preprocessing stage includes:

- Data cleaning
- Handling missing values
- Data type optimization
- Feature engineering
- Data validation
- Exporting the final analytics dataset

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/raw/ecommerce_dataset_+1m.csv")

In [3]:
df["order_date"] = pd.to_datetime(df["order_date"])
df["account_creation_date"] = pd.to_datetime(df["account_creation_date"])

In [4]:
missing = (
    df.isna()
      .sum()
      .to_frame("Missing")
)

missing["Percentage"] = (
    missing["Missing"] / len(df)
) * 100

missing.sort_values(
    "Missing",
    ascending=False
)

                        Missing  Percentage
return_reason            900244   90.013328
coupon_code              500083   50.002150
customer_feedback        199617   19.959245
order_month                   0    0.000000
order_year                    0    0.000000
...                         ...         ...
abandoned_cart_before         0    0.000000
fraud_risk_score              0    0.000000
profit_margin_percent         0    0.000000
order_priority                0    0.000000
support_ticket_created        0    0.000000

[62 rows x 2 columns]

In [5]:
df["return_reason"] = df["return_reason"].fillna("Not Returned")

df["coupon_code"] = df["coupon_code"].fillna("No Coupon")

df["customer_feedback"] = df["customer_feedback"].fillna("No Feedback")

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 1000123 entries, 0 to 1000122
Data columns (total 62 columns):
 #   Column                    Non-Null Count    Dtype
---  ------                    --------------    -----
 0   order_id                  1000123 non-null  str
 1   order_date                1000123 non-null  datetime64[us]
 2   order_year                1000123 non-null  int64
 3   order_month               1000123 non-null  int64
 4   order_day                 1000123 non-null  int64
 5   order_hour                1000123 non-null  int64
 6   order_minute              1000123 non-null  int64
 7   order_second              1000123 non-null  int64
 8   is_weekend                1000123 non-null  str
 9   order_status              1000123 non-null  str
 10  return_reason             1000123 non-null  str
 11  customer_id               1000123 non-null  str
 12  customer_name             1000123 non-null  str
 13  gender                    1000123 non-null  str
 14  age                       1000123 non-null  int64
 15  customer_segment          1000123 non-null  str
 16  country                   1000123 non-null  str
 17  city                      1000123 non-null  str
 18  customer_loyalty_score    1000123 non-null  float64
 19  total_orders_by_customer  1000123 non-null  int64
 20  account_creation_date     1000123 non-null  datetime64[us]
 21  product_id                1000123 non-null  str
 22  product_name              1000123 non-null  str
 23  category                  1000123 non-null  str
 24  sub_category              1000123 non-null  str
 25  brand                     1000123 non-null  str
 26  product_rating_avg        1000123 non-null  float64
 27  product_reviews_count     1000123 non-null  int64
 28  stock_quantity            1000123 non-null  int64
 29  unit_price_usd            1000123 non-null  float64
 30  quantity                  1000123 non-null  int64
 31  discount_percent          1000123 non-null  int64
 32  discount_amount_usd       1000123 non-null  float64
 33  total_price_usd           1000123 non-null  float64
 34  cost_usd                  1000123 non-null  float64
 35  profit_usd                1000123 non-null  float64
 36  tax_usd                   1000123 non-null  float64
 37  currency                  1000123 non-null  str
 38  payment_method            1000123 non-null  str
 39  payment_status            1000123 non-null  str
 40  installment_plan          1000123 non-null  str
 41  shipping_method           1000123 non-null  str
 42  shipping_cost_usd         1000123 non-null  float64
 43  delivery_days             1000123 non-null  int64
 44  shipping_country          1000123 non-null  str
 45  warehouse_location        1000123 non-null  str
 46  delivery_status           1000123 non-null  str
 47  rating                    1000123 non-null  int64
 48  review_sentiment          1000123 non-null  str
 49  customer_feedback         1000123 non-null  str
 50  coupon_used               1000123 non-null  str
 51  coupon_code               1000123 non-null  str
 52  campaign_source           1000123 non-null  str
 53  device_type               1000123 non-null  str
 54  traffic_source            1000123 non-null  str
 55  session_duration_minutes  1000123 non-null  float64
 56  pages_visited             1000123 non-null  int64
 57  abandoned_cart_before     1000123 non-null  str
 58  fraud_risk_score          1000123 non-null  float64
 59  profit_margin_percent     1000123 non-null  float64
 60  order_priority            1000123 non-null  str
 61  support_ticket_created    1000123 non-null  str
dtypes: datetime64[us](2), float64(12), int64(15), str(33)
memory usage: 1.9 GB

```Feature Engineering```

```Profit per Unit```

In [10]:
df["profit_per_unit"] = (
    df["profit_usd"]
    / df["quantity"]
)

df["profit_per_unit"].head(2)

0    31.08
1    17.39
Name: profit_per_unit, dtype: float64

```Revenue per Unit```

In [12]:
df["revenue_per_unit"] = (
    df["total_price_usd"]
    / df["quantity"]
)

df["revenue_per_unit"].head(2)

0    108.46
1     51.28
Name: revenue_per_unit, dtype: float64

```Customer Age Groups```

In [14]:
df["age_group"] = pd.cut(

    df["age"],

    bins=[18,25,35,45,55,65,100],

    labels=[
        "18-25",
        "26-35",
        "36-45",
        "46-55",
        "56-65",
        "65+"
    ]

)

```Order Month Name```

In [15]:
df["month_name"] = (
    df["order_date"]
    .dt.month_name()
)

```Quarter```

In [16]:
df["quarter"] = (
    df["order_date"]
    .dt.quarter
)

```Weekend Order```

In [17]:
df["is_weekend"] = (
    df["order_date"]
    .dt.dayofweek >= 5
)

```High Value Order```

In [19]:
df["high_value_order"] = (
    df["total_price_usd"] >= 1000
)

In [20]:
df.info()

df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 1000123 entries, 0 to 1000122
Data columns (total 68 columns):
 #   Column                    Non-Null Count    Dtype
---  ------                    --------------    -----
 0   order_id                  1000123 non-null  str
 1   order_date                1000123 non-null  datetime64[us]
 2   order_year                1000123 non-null  int64
 3   order_month               1000123 non-null  int64
 4   order_day                 1000123 non-null  int64
 5   order_hour                1000123 non-null  int64
 6   order_minute              1000123 non-null  int64
 7   order_second              1000123 non-null  int64
 8   is_weekend                1000123 non-null  bool
 9   order_status              1000123 non-null  str
 10  return_reason             1000123 non-null  str
 11  customer_id               1000123 non-null  str
 12  customer_name             1000123 non-null  str
 13  gender                    1000123 non-null  str
 14  age                       1000123 non-null  int64
 15  customer_segment          1000123 non-null  str
 16  country                   1000123 non-null  str
 17  city                      1000123 non-null  str
 18  customer_loyalty_score    1000123 non-null  float64
 19  total_orders_by_customer  1000123 non-null  int64
 20  account_creation_date     1000123 non-null  datetime64[us]
 21  product_id                1000123 non-null  str
 22  product_name              1000123 non-null  str
 23  category                  1000123 non-null  str
 24  sub_category              1000123 non-null  str
 25  brand                     1000123 non-null  str
 26  product_rating_avg        1000123 non-null  float64
 27  product_reviews_count     1000123 non-null  int64
 28  stock_quantity            1000123 non-null  int64
 29  unit_price_usd            1000123 non-null  float64
 30  quantity                  1000123 non-null  int64
 31  discount_percent          1000123 non-null  int64
 32  discount_amount_usd       1000123 non-null  float64
 33  total_price_usd           1000123 non-null  float64
 34  cost_usd                  1000123 non-null  float64
 35  profit_usd                1000123 non-null  float64
 36  tax_usd                   1000123 non-null  float64
 37  currency                  1000123 non-null  str
 38  payment_method            1000123 non-null  str
 39  payment_status            1000123 non-null  str
 40  installment_plan          1000123 non-null  str
 41  shipping_method           1000123 non-null  str
 42  shipping_cost_usd         1000123 non-null  float64
 43  delivery_days             1000123 non-null  int64
 44  shipping_country          1000123 non-null  str
 45  warehouse_location        1000123 non-null  str
 46  delivery_status           1000123 non-null  str
 47  rating                    1000123 non-null  int64
 48  review_sentiment          1000123 non-null  str
 49  customer_feedback         1000123 non-null  str
 50  coupon_used               1000123 non-null  str
 51  coupon_code               1000123 non-null  str
 52  campaign_source           1000123 non-null  str
 53  device_type               1000123 non-null  str
 54  traffic_source            1000123 non-null  str
 55  session_duration_minutes  1000123 non-null  float64
 56  pages_visited             1000123 non-null  int64
 57  abandoned_cart_before     1000123 non-null  str
 58  fraud_risk_score          1000123 non-null  float64
 59  profit_margin_percent     1000123 non-null  float64
 60  order_priority            1000123 non-null  str
 61  support_ticket_created    1000123 non-null  str
 62  profit_per_unit           1000123 non-null  float64
 63  revenue_per_unit          1000123 non-null  float64
 64  age_group                 982881 non-null   category
 65  month_name                1000123 non-null  str
 66  quarter                   1000123 non-null  int32
 67  high_value_order          1000123 non-null  bool
dtypes: bool(2), category(1), datetime64[us](2), float64(14), int32(1), int64(15), str(33)
memory usage: 495.0 MB

,order_date,order_year,order_month,order_day,order_hour,order_minute,order_second,age,customer_loyalty_score,total_orders_by_customer,...,shipping_cost_usd,delivery_days,rating,session_duration_minutes,pages_visited,fraud_risk_score,profit_margin_percent,profit_per_unit,revenue_per_unit,quarter
count,1000123,1.000123e+06,1.000123e+06,1.000123e+06,1.000123e+06,1.000123e+06,1.000123e+06,1.000123e+06,1.000123e+06,1.000123e+06,...,1.000123e+06,1.000123e+06,1.000123e+06,1.000123e+06,1.000123e+06,1.000123e+06,1.000123e+06,1.000123e+06,1.000123e+06,1.000123e+06
mean,2025-02-02 09:03:08.087075,2.024590e+03,6.514849e+00,1.575253e+01,1.148814e+01,2.949467e+01,2.948548e+01,4.649414e+01,4.997252e+01,2.548700e+01,...,1.250445e+01,7.506648e+00,2.999784e+00,3.051033e+01,1.050609e+01,4.996161e+01,3.946517e+01,5.368110e+01,1.345128e+02,2.506289e+00
min,2024-02-03 04:31:57.621140,2.024000e+03,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.800000e+01,0.000000e+00,1.000000e+00,...,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,6.660000e+00,5.566667e-01,7.506667e+00,1.000000e+00
25%,2024-08-03 07:06:13.445032,2.024000e+03,4.000000e+00,8.000000e+00,5.000000e+00,1.400000e+01,1.400000e+01,3.200000e+01,2.490000e+01,1.300000e+01,...,6.260000e+00,4.000000e+00,2.000000e+00,1.570000e+01,6.000000e+00,2.500000e+01,3.169000e+01,2.231000e+01,6.316500e+01,2.000000e+00
50%,2025-02-02 15:43:25.252944,2.025000e+03,7.000000e+00,1.600000e+01,1.100000e+01,3.000000e+01,2.900000e+01,4.600000e+01,5.000000e+01,2.500000e+01,...,1.250000e+01,8.000000e+00,3.000000e+00,3.050000e+01,1.100000e+01,5.000000e+01,3.990000e+01,4.254500e+01,1.136150e+02,3.000000e+00
75%,2025-08-04 04:36:28.450373,2.025000e+03,1.000000e+01,2.300000e+01,1.700000e+01,4.400000e+01,4.400000e+01,6.100000e+01,7.500000e+01,3.800000e+01,...,1.874000e+01,1.100000e+01,4.000000e+00,4.530000e+01,1.600000e+01,7.490000e+01,4.817000e+01,7.188200e+01,1.795500e+02,4.000000e+00
max,2026-02-02 16:03:01.727725,2.026000e+03,1.200000e+01,3.100000e+01,2.300000e+01,5.900000e+01,5.900000e+01,7.500000e+01,1.000000e+02,5.000000e+01,...,2.500000e+01,1.400000e+01,5.000000e+00,6.000000e+01,2.000000e+01,1.000000e+02,6.002000e+01,2.996200e+02,5.000000e+02,4.000000e+00
std,NaN,5.758891e-01,3.448711e+00,8.799790e+00,6.918078e+00,1.730984e+01,1.732781e+01,1.673373e+01,2.889377e+01,1.443421e+01,...,7.216416e+00,4.032930e+00,1.414973e+00,1.703368e+01,5.766207e+00,2.884771e+01,1.094131e+01,4.316658e+01,9.581086e+01,1.117116e+00

In [21]:
df.head()

,order_id,order_date,order_year,order_month,order_day,order_hour,order_minute,order_second,is_weekend,order_status,...,fraud_risk_score,profit_margin_percent,order_priority,support_ticket_created,profit_per_unit,revenue_per_unit,age_group,month_name,quarter,high_value_order
0,ORD-XAJI0,2024-10-14 11:20:05.496679,2024,10,14,11,20,5,False,Completed,...,45.3,28.66,Medium,Yes,31.08,108.46,46-55,October,4,False
1,ORD-NHJ7X,2024-10-21 00:49:44.681065,2024,10,21,0,49,44,False,Completed,...,97.1,33.91,Low,Yes,17.39,51.28,56-65,October,4,False
2,ORD-YTJXE,2025-03-17 19:49:36.983317,2025,3,17,19,49,36,False,Completed,...,43.8,52.77,High,No,156.15,295.89,46-55,March,1,False
3,ORD-EIMVI,2024-09-27 06:24:44.913768,2024,9,27,6,24,44,False,Completed,...,96.9,38.15,Low,Yes,71.09,186.33,46-55,September,3,False
4,ORD-OR56F,2025-05-21 17:10:48.401882,2025,5,21,17,10,48,False,Completed,...,45.8,33.05,High,Yes,127.05,384.44,26-35,May,2,False

In [22]:
df.shape

(1000123, 68)

```Explore the dataset```

In [23]:
df.to_csv(
    "../data/processed/ecommerce_cleaned.csv",
    index=False
)

## Preprocessing Summary

The dataset was prepared for downstream SQL analysis and Power BI dashboard development.

The preprocessing process included:

- Converting date columns
- Handling logical missing values
- Removing duplicate records
- Optimizing data types
- Creating business-focused features
- Exporting a cleaned analytics dataset

The resulting dataset is optimized for database storage, SQL querying, and business intelligence reporting.